# This is a sample of the main settings file. 
# It should go into HOMEDIR/.config/VisionBasedRobotManipulator/mainsettings.yaml
# Change the path here to run different configurations on different machines. 
configpath: "/path/to/the/setting.yaml"
